services:
  - type: web
    name: your-backend-service
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: your_mongo_uri_value
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: CLIENT_URL
        value: http://localhost:5173
